
-- Check for existing proposals generated by the agent
SELECT id, actor_type, proposal_type, status, created_at, data->>'suggested_quantity' as suggested_qty 
FROM proposals 
WHERE actor_type = 'agent' 
ORDER BY created_at DESC 
LIMIT 5;

-- Check inventory items that are currently below par_min (candidates for proposals)
SELECT bi.branch_id, i.name, bi.current_stock, bi.par_min 
FROM branch_inventory bi
JOIN ingredients i ON bi.ingredient_id = i.id
WHERE bi.current_stock < bi.par_min
LIMIT 5;
